#pragma once

#include "quantum.h"

// Defines the keycodes used by our macros in process_record_user
enum custom_keycodes {
    CH_CUSTOM = SAFE_RANGE,
    // zoom win
    CH_ZOOM_MUTE_TOGGLE_WIN,
    CH_ZOOM_VIDEO_TOGGLE_WIN,
    CH_ZOOM_SHARE_SCREEN_TOGGLE_WIN,
    CH_ZOOM_RAISE_HAND_TOGGLE_WIN,
    CH_ZOOM_LEAVE_MEETING_WIN,
    // zoom mac
    CH_ZOOM_MUTE_TOGGLE_MAC,
    CH_ZOOM_VIDEO_TOGGLE_MAC,
    CH_ZOOM_SHARE_SCREEN_TOGGLE_MAC,
    CH_ZOOM_RAISE_HAND_TOGGLE_MAC,
    CH_ZOOM_LEAVE_MEETING_MAC,
    // teams win
    CH_TEAMS_MUTE_TOGGLE_WIN,
    CH_TEAMS_VIDEO_TOGGLE_WIN,
    CH_TEAMS_SHARE_SCREEN_TOGGLE_WIN,
    CH_TEAMS_RAISE_HAND_TOGGLE_WIN,
    CH_TEAMS_LEAVE_MEETING_WIN,
    // teams mac
    CH_TEAMS_MUTE_TOGGLE_MAC,
    CH_TEAMS_VIDEO_TOGGLE_MAC,
    CH_TEAMS_SHARE_SCREEN_TOGGLE_MAC,
    CH_TEAMS_RAISE_HAND_TOGGLE_MAC,
    CH_TEAMS_LEAVE_MEETING_MAC,
    // skype win
    CH_SKYPE_MUTE_TOGGLE_WIN,
    CH_SKYPE_VIDEO_TOGGLE_WIN,
    CH_SKYPE_SHARE_SCREEN_TOGGLE_WIN,
    CH_SKYPE_RAISE_HAND_TOGGLE_WIN,
    CH_SKYPE_LEAVE_MEETING_WIN,
    // skype mac
    CH_SKYPE_MUTE_TOGGLE_MAC,
    CH_SKYPE_VIDEO_TOGGLE_MAC,
    CH_SKYPE_SHARE_SCREEN_TOGGLE_MAC,
    CH_SKYPE_RAISE_HAND_TOGGLE_MAC,
    CH_SKYPE_LEAVE_MEETING_MAC,
    // google meet win
    CH_GOOGLE_MEET_MUTE_TOGGLE_WIN,
    CH_GOOGLE_MEET_VIDEO_TOGGLE_WIN,
    CH_GOOGLE_MEET_SHARE_SCREEN_TOGGLE_WIN,
    CH_GOOGLE_MEET_RAISE_HAND_TOGGLE_WIN,
    CH_GOOGLE_MEET_LEAVE_MEETING_WIN,
    // google meet mac
    CH_GOOGLE_MEET_MUTE_TOGGLE_MAC,
    CH_GOOGLE_MEET_VIDEO_TOGGLE_MAC,
    CH_GOOGLE_MEET_SHARE_SCREEN_TOGGLE_MAC,
    CH_GOOGLE_MEET_RAISE_HAND_TOGGLE_MAC,
    CH_GOOGLE_MEET_LEAVE_MEETING_MAC,
    // switch window
    CH_SWITCH_WINDOW_WIN,
    CH_SWITCH_WINDOW_MAC,
    // rest
    CH_VOLUME_UP,
    CH_VOLUME_DOWN,
    CH_MEDIA_NEXT,
    CH_MEDIA_PLAY_PAUSE,
    CH_LAST_KEYCODE
};
